const ADD_NOTE = "ADD-NOTE";
const EDIT_NOTE = "EDIT-NOTE";
const DELETE_NOTE = "DELETE-NOTE";
const UPDATE_NOTE = "UPDATE-NOTE";
const CLEAR_NOTES = "CLEAR-NOTES";

export { ADD_NOTE, DELETE_NOTE, UPDATE_NOTE, CLEAR_NOTES, EDIT_NOTE };
